# Generated by Django 3.2 on 2023-04-09 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalog',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='file',
            field=models.ImageField(upload_to='media/products/'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['catalog'], name='catalog_pro_catalog_35930a_idx'),
        ),
        migrations.AddIndex(
            model_name='productimage',
            index=models.Index(fields=['product'], name='catalog_pro_product_f7f0eb_idx'),
        ),
        migrations.AddIndex(
            model_name='productparam',
            index=models.Index(fields=['name', 'value'], name='catalog_pro_name_3b5029_idx'),
        ),
        migrations.AddIndex(
            model_name='productparam',
            index=models.Index(fields=['product'], name='catalog_pro_product_5d3ccf_idx'),
        ),
    ]
